/* eslint-disable new-cap */
/* eslint-disable camelcase */
import Navigation from "./components/Navigation";
import Footer from "./components/Footer";
import "./globals.css";
import { Playfair_Display, Abril_Fatface } from "next/font/google";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});
const abril = Abril_Fatface({
  subsets: ["latin"],
  variable: "--font-abril",
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hans" className={`${abril.variable} ${playfair.variable}`}>
      <body className="bg-mj-black text-white">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
